# Run unit tests for Python Veracity SDK in Azure DevOps

trigger:
  batch: true

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'

variables:
- name: PYTHONPATH
  value: src

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest==7.0.1 pytest-azurepipelines pytest-asyncio pytest-cov
  displayName: 'Install dependencies'

- script: |
    pytest --junitxml=junit/test-results.xml --cov=./src/plexosdhs --cov-report=xml
  displayName: 'Run unit tests with pytest'
